/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../../src/layout/components/Breadcrumb.vue')['default']
    CodeMirror: typeof import('./../../src/components/auto/CodeMirror.vue')['default']
    'Fa6Solid:desktop': typeof import('~icons/fa6-solid/desktop')['default']
    Fa6SolidBroom: typeof import('~icons/fa6-solid/broom')['default']
    Fa6Solidcopy: typeof import('~icons/fa6-solid/copy')['default']
    Fa6SolidDesktop: typeof import('~icons/fa6-solid/desktop')['default']
    Fa6SolidUpload: typeof import('~icons/fa6-solid/upload')['default']
    Header: typeof import('./../../src/layout/components/Header.vue')['default']
    Main: typeof import('./../../src/layout/components/Main.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NP: typeof import('naive-ui')['NP']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NText: typeof import('naive-ui')['NText']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
